baseurl = "https://joeyworld.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "ko-KR"
layoutdir = "layouts"
publishdir = "public"
author = "Byeong Gyu Choi"
title = "JoeyLog"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Django, Node, React를 합니다. 머신러닝, 특히 NLP에 관심이 매우 많습니다."
copyright = "Copyright © 2017 Byeong Gyu Choi"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/profile.jpg"
faviconfile = "img/profile.jpg"
highlightjs = true
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "joeyworld"
email = "bisschoi9541@gmail.com"
linkedin = "병규-최-43290213b"
# twitter = "example"
facebook = "joeyworldd"
# social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
githubRepo = "joeyworld/joeyworld.github.io/tree/master"
small_banner_logo = false
